name: Deploy to Server via FTPS

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy PHP site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload via FTPS (explicit TLS/SSL)
        uses: airvzxf/ftp-deployment-action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          remote_dir: "./"
          delete: "false"
          max_retries: "7"
          no_symlinks: "false"
          ftp_ssl_allow: "true"
          ssl_verify_certificate: "true"
          ssl_check_hostname: "false"
          net_persist_retries: "11"
          net_timeout: "20s"